---

- name: install add-apt-repository
  apt: pkg=python-software-properties state=latest
  sudo: yes

- name: add updated nginx repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx' state=present
  sudo: yes

- name: add nginx apt public key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xABF5BD827BD9BF62 state=present
  sudo: yes

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
      - git
      - vim
      - fail2ban
      - ufw
      - nginx
      - curl
      - wget
      - zip
      - rsync

- name: install nginx config
  sudo: yes
  copy: src=conf/ayai.conf dest=/etc/nginx/conf.d/default

- name: ensure fail2ban is on
  sudo: yes
  action: service name=fail2ban state=restarted enabled=yes

- name: forbid root ssh
  sudo: yes
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart ssh

- name: reset firewall
  sudo: yes
  action: shell ufw --force reset

- name: allow firewall authorized ports
  sudo: yes
  action: shell ufw allow {{ item }}
  with_items:
    - 22
    - 80

- name: enable firewall
  sudo: yes
  action: shell ufw --force enable
