---

- include_vars: main.yml

- name: Create project directory
  file: state=directory path={{project_root}}

- name: Pull frontend code
  git: repo={{project_repo}} dest={{project_root}} version={{branch}}


